#? Config file for btop v.1.4.6

#* Name of a btop theme file, "Default" and "TTY" for builtin themes.
color_theme = "current"

#* If the theme set background should be shown, set to False if you want terminal background transparency.
theme_background = true

#* Sets if 24-bit truecolor should be used.
truecolor = true

#* Force tty mode.
force_tty = false

#* Define presets for the layout of the boxes.
presets = "cpu:1:default,proc:0:default cpu:0:default,mem:0:default,net:0:default cpu:0:block,net:0:tty"

#* Vim keys navigation (h,j,k,l,g,G)
vim_keys = true

#* Rounded corners on boxes.
rounded_corners = true

#* Terminal synchronized output.
terminal_sync = true

#* Graph symbols.
graph_symbol = "braille"
graph_symbol_cpu = "default"
graph_symbol_gpu = "default"
graph_symbol_mem = "default"
graph_symbol_net = "default"
graph_symbol_proc = "default"

#* Shown boxes
shown_boxes = "cpu mem net proc"

#* Update interval in milliseconds
update_ms = 2000

#* Processes box filtering and sorting
proc_sorting = "cpu lazy"
proc_reversed = false
proc_tree = false
proc_colors = true
proc_gradient = true
proc_per_core = false
proc_mem_bytes = true
proc_cpu_graphs = true
proc_info_kernel = false

#* CPU box settings
cpu_bottom = false
cpu_custom_subboxes = ""
cpu_core_map = ""
cpu_sensor = "Auto"
show_uptime = true
check_temp = true
cpu_single_graph = false
show_coretemp = true
temp_scale = "celsius"

#* Memory box settings
mem_graphs = true
mem_below_net = false
zfs_arc_cached = true
show_swap = true
swap_disk = true
show_disks = true
only_physical = true
use_fstab = true
zfs_hide_datasets = false
disk_free_priv = false

#* Network box settings
net_download = "100M"
net_upload = "100M"
net_auto = true
net_sync = true
net_iface = ""

#* Show battery stats if available
show_battery = true
selected_battery = "Auto"

#* Log level
log_level = "WARNING"
