# Extra autostart processes
# exec-once = uwsm-app -- my-service

# Animated 4K Video Wallpaper (inicia automaticamente se houver vídeo em ~/.config/hypr/wallpapers/)
exec-once = ~/Projects/dotfiles/scripts/set-animated-wallpaper.sh
