# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {



}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 13
}

animations {
  enabled = true

  # Define an easing curve you can reuse by name
  bezier = ease, 0.05, 0.9, 0.1, 1.0

  # Core groups commonly available
  animation = windows, 1, 7, ease
  animation = windowsOut, 1, 7, ease
  animation = border, 1, 7, ease
  animation = borderangle, 1, 7, ease
  animation = fade, 1, 7, ease
  animation = workspaces, 1, 5, ease, slide
}

decoration {



}

dwindle {
    force_split = 0
}
